AllCops:
  Exclude:
    - db/*
    - db/migrate/*.rb
    - 'spec/**/*.rb'
    - config/environments/*.rb
    - bin/*
Style/StringLiterals:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
