defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/ruby:2.6.3-node
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH:  vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: postgres
        RAILS_ENV: test
    - image: circleci/postgres:9.4-alpine
      environment:
        POSTGRES_USER: postgres
        POSTGRES_DB: whether_sweater_test
        POSTGRES_PASSWORD: ""

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
            bundle install
      - run:
          name: db setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: rpsec testing
          command: |
            mkdir -p /tmp/test-results
            bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: /tmp/test-results
